{% set name = "nashpy" %}
{% set version = "0.0.37" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nashpy-{{ version }}.tar.gz
  sha256: 3411e8a9c0239830c16a6c92b13c31d4c654ee22a27cf26cc8333fea61174613

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core >=2,<4
  run:
    - python >=3.8
    - numpy >=1.21.0
    - scipy >=0.19.0

test:
  imports:
    - nashpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://vknight.org
  summary: A library with algorithms on 2 player games
  license: MIT
  license_file: LICENSE
  description: |
    A library with algorithms on 2 player games.

    PyPI: [https://pypi.org/project/nashpy](https://pypi.org/project/nashpy)

  doc_url: https://nashpy.readthedocs.io/en/stable/
  dev_url: https://github.com/drvinceknight/Nashpy/tree/main

extra:
  recipe-maintainers:
    - sugatoray
